import { SubscriptionPlan } from "../../../../domain/entities/subscription-plan.entity";
import { ConflictError } from "../../../../domain/errors/errors";
import { ISubscriptionPlanRepository } from "../../../../domain/interfaces/repositories/subscription-plan/ISubscriptionPlanRepository";

export interface CreateSubscriptionPlanRequest {
  name: string;
  price: number;
  billingCycle: "monthly" | "yearly";
  features: string[];
  isActive?: boolean;
}

export class CreateSubscriptionPlanUseCase {
  constructor(
    private readonly subscriptionPlanRepository: ISubscriptionPlanRepository,
  ) {}

  async execute(
    data: CreateSubscriptionPlanRequest,
  ): Promise<SubscriptionPlan> {
    const existing = await this.subscriptionPlanRepository.findByName(
      data.name.trim(),
    );

    if (existing) {
      throw new ConflictError("A subscription plan with this name already exists");
    }

    const plan = SubscriptionPlan.create({
      id: "", // auto-generated by mongodb
      name: data.name.trim(),
      price: data.price,
      billingCycle: data.billingCycle,
      features: data.features,
      subscriberCount: 0,
      isActive: data.isActive ?? true,
    });

    return this.subscriptionPlanRepository.create(plan);
  }
}
